name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://pandoc/latex:3
        with:
          args: "--help"
      - uses: docker://eguchi1611/texlive-sci-ja
        with:
          args: "uplatex --version"
