name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile LaTeX documents
        uses: docker://eguchi1611/texlive-sci-ja
        with:
          args: "latexmk -r .latexmkrc main.tex"
      - uses: actions/upload-artifact@v4
        with:
          path: main.pdf
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: afdc130c46cc37864df7a03b15278775
          command: pages deploy . --project-name latex-actions-sample
