name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://eguchi1611/texlive-sci-ja
        with:
          args: "latexmk -r .latexmkrc main.tex"
